name: Deploy ZERO13 Indonesia

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, dom, fileinfo, mysql
        
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Copy .env
      run: php -r "copy('.env.example', '.env');"
      
    - name: Install Composer dependencies
      run: composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist
      
    - name: Generate key
      run: php artisan key:generate
      
    - name: Install NPM dependencies
      run: npm ci
      
    - name: Build assets
      run: npm run build
      
    - name: Deploy to Hostinger
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd /home/zero13indonesia/domains/zero13indonesia.com/public_html
          git pull origin main
          composer install --no-dev --optimize-autoloader --no-interaction
          npm ci
          npm run build
          cp .env.production .env
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          php artisan migrate --force
          chmod -R 755 storage
          chmod -R 755 bootstrap/cache
          echo "🚀 ZERO13 Indonesia deployed successfully!"